In [1]:
pip list

Package               Version
--------------------- ------------
asttokens             3.0.2
attrs                 26.1.0
beautifulsoup4        4.15.0
bs4                   0.0.2
certifi               2026.7.22
cffi                  2.1.1
charset-normalizer    3.5.1
colorama              0.4.6
comm                  0.2.3
debugpy               1.8.22
decorator             5.3.1
exceptiongroup        1.3.1
executing             2.2.1
google-play-scraper   1.2.7
google_search_results 2.4.2
h11                   0.16.0
idna                  3.20
ipykernel             7.3.0
ipython               8.39.0
jedi                  0.20.0
jupyter_client        8.10.0
jupyter_core          5.9.1
matplotlib-inline     0.2.2
nest-asyncio2         1.7.2
numpy                 2.2.6
outcome               1.3.0.post0
packaging             26.3
pandas                2.3.3
parso                 0.8.7
pip                   23.0.1
platformdirs          4.11.11
prompt_toolkit        3.0.53
psutil                7.2.2
pure_eval             0.2.4
pycparser             3.0
Pygments              2.21.0
PySocks               1.7.1
python-dateutil       2.9.0.post0
pytz                  2026.3.post1
pyzmq                 27.2.0
requests              2.34.2
selenium              4.49.0
serpapi               1.1.1
setuptools            65.5.0
six                   1.17.0
sniffio               1.3.1
sortedcontainers      2.4.0
soupsieve             2.9.2
stack-data            0.6.3
tornado               6.5.10
traitlets             5.16.1
trio                  0.34.0
trio-websocket        0.12.2
typing_extensions     4.16.0
tzdata                2026.4
urllib3               2.8.0
wcwidth               0.8.4
websocket-client      1.9.2
wsproto               1.3.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [16]:
import pandas as pd
from pathlib import Path

base_dir = Path().resolve().parent
df = pd.read_csv(base_dir / "data" / "dataset_reviews_scraper_gplay.csv")
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,0e681ed9-8c43-4dec-8d67-50a2159ab586,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Seringkali mau transfer ke bank lain tapi sela...,1,9,3.0.0,2026-07-10 20:05:31,NaN,NaN,3.0.0
1,7eac364a-6fce-4965-b720-321b6831ce82,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Banyak fitur sederhana yang error di applikasi...,2,1,NaN,2026-09-02 02:38:19,NaN,NaN,NaN
2,4f5734a9-b235-45a8-b977-f3d1052e443c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Menurut saya, aplikasi Pospay sangat membantu ...",5,0,2.16.16,2026-09-12 17:54:15,NaN,NaN,2.16.16
3,7c3a85c2-0392-418c-822c-a0122b2d860e,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi yang sangat memudahkan untuk bayar-ba...,5,4,2.16.16,2026-08-24 11:26:31,NaN,NaN,2.16.16
4,3bb8426d-b5b5-4dd4-a9eb-62a6428f3eb7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Servernya sering error, banyak kendala terkait...",1,45,2.16.7,2024-09-03 09:53:43,"Halo , maaf atas kendalanya ya. Untuk memberik...",2024-09-04 15:04:52,2.16.7
...,...,...,...,...,...,...,...,...,...,...,...
4995,e8ae6988-700b-45d7-a54e-11d81c02547d,Erna Juwita,https://play-lh.googleusercontent.com/a/ACg8oc...,Lama sekali loading pengambilan foto untuk BSU...,1,1,2.10.4,2022-11-04 08:34:38,NaN,NaN,2.10.4
4996,4669cdb4-a2b4-490a-991a-3d6e962f9ac5,News Math,https://play-lh.googleusercontent.com/a/ACg8oc...,Saya pernah uninstall pospay lalu install lagi...,4,0,NaN,2024-10-16 21:50:58,NaN,NaN,NaN
4997,828737ba-4360-4fda-a471-24d6dbf15187,Silvia Fani,https://play-lh.googleusercontent.com/a-/ALV-U...,Setelah d upgrade malah eror terus gangguan tr...,1,0,1.12.37,2021-04-20 22:50:26,"Hai Sobat Pospay, Kami mohon maaf atas ketidak...",2021-05-28 10:01:16,1.12.37
4998,16cdde15-9a28-441e-8abc-0a1da1abadb0,Roland,https://play-lh.googleusercontent.com/a/ACg8oc...,"Aplikasinya bagus, memudahkan dalam transaksi ...",5,0,1.11.0,2021-01-06 11:22:21,"Hai Sobat Posgiro Mobile, terima kasih atas ke...",2021-01-06 13:11:34,1.11.0
4999,59c914d2-d7c4-4fd9-b78a-1b376e5785bb,Noviah,https://play-lh.googleusercontent.com/a/ACg8oc...,"Aplikasi TOLOL, Upgrad Reguler gak Bisa Bisa F...",1,1,2.16.5,2024-07-09 00:59:35,NaN,NaN,2.16.5

In [18]:
base_dir = Path().resolve().parent
df = pd.read_csv(base_dir / "data" / "tokped_reviews.csv")
df

,Review,Rating,Tanggal
0,semoga cowo aku suka yaa,bintang 5,Hari ini
1,bagus mantep,bintang 5,Hari ini
2,Mantappp keren bnget awwwwwwwww,bintang 5,Hari ini
3,Cakep,bintang 5,Hari ini
4,Ok,bintang 5,Hari ini
...,...,...,...
90,Kwalitas ORI. Smga tambah semangat buat runnin...,bintang 5,1 minggu lalu
91,Bentuk dan ukuran: ok,bintang 4,1 minggu lalu
92,baguss bangett sukaa makasiiii KickAvenue 🫶🏻,bintang 5,1 minggu lalu
93,"Kurang nyaman dipake sepatu yg sebelah kanan ,...",bintang 4,1 minggu lalu
94,Bentuk dan ukuran: Pass,bintang 5,1 minggu lalu

In [22]:
base_dir = Path().resolve().parent
df = pd.read_csv(base_dir / "data" / "gmaps_reviews.csv")
df

,page,name,link,thumbnail,rating,date,snippet,images,local_guide
0,1,Dimas Wahyu Wibisono,https://www.google.com/maps/contrib/1140604425...,https://lh3.googleusercontent.com/a-/ALV-UjWgl...,5.0,11 bulan lalu,"Tempatnya nyaman dan tenang, karena ga terlalu...",['https://lh3.googleusercontent.com/grass-cs/A...,True
1,1,Lilis Maryani,https://www.google.com/maps/contrib/1148450311...,https://lh3.googleusercontent.com/a-/ALV-UjXXz...,4.0,setahun lalu,"Tempatnya nyaman, lumayan luas, ada indoor ada...",['https://lh3.googleusercontent.com/grass-cs/A...,True
2,1,Abu Thalhah,https://www.google.com/maps/contrib/1065823026...,https://lh3.googleusercontent.com/a-/ALV-UjX2Q...,4.0,3 tahun lalu,"Kalau keluar dari Tol Pasteur, langsung belok ...",['https://lh3.googleusercontent.com/grass-cs/A...,True
3,1,Nia Rahma,https://www.google.com/maps/contrib/1059863333...,https://lh3.googleusercontent.com/a-/ALV-UjWy9...,5.0,setahun lalu,"Tempat nya bagus, nyaman buat duduk rame - ram...",['https://lh3.googleusercontent.com/grass-cs/A...,True
4,1,Ronald Fadzry,https://www.google.com/maps/contrib/1145053838...,https://lh3.googleusercontent.com/a-/ALV-UjUWp...,5.0,4 tahun lalu,Alhamdulillah Baru coba 3 menu ini ;\n(Korean ...,['https://lh3.googleusercontent.com/grass-cs/A...,True
...,...,...,...,...,...,...,...,...,...
73,8,Muhamad Cahyadi,https://www.google.com/maps/contrib/1072703912...,https://lh3.googleusercontent.com/a-/ALV-UjVjs...,5.0,4 tahun lalu,NaN,NaN,NaN
74,8,Margaretha Mitsi,https://www.google.com/maps/contrib/1127944359...,https://lh3.googleusercontent.com/a-/ALV-UjU3x...,5.0,4 tahun lalu,NaN,NaN,NaN
75,9,adree nc,https://www.google.com/maps/contrib/1184051787...,https://lh3.googleusercontent.com/a-/ALV-UjXRv...,4.0,4 tahun lalu,NaN,NaN,NaN
76,9,Ciextali25,https://www.google.com/maps/contrib/1119147285...,https://lh3.googleusercontent.com/a-/ALV-UjVFx...,5.0,4 tahun lalu,NaN,NaN,NaN
77,9,Ichsan Nurfajar,https://www.google.com/maps/contrib/1100517616...,https://lh3.googleusercontent.com/a-/ALV-UjUrU...,5.0,4 tahun lalu,NaN,NaN,NaN